- hosts: node01
  gather_facts: true
  vars:
    my_name: Shawn

  vars_prompt:
    name: user
    prompt: Enter Username
    private: no
    
  tasks:
    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "RedHat"

    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "Amazon"


    - apt:
        pkg: apache2
        state: installed
      when: ansible_distribution == "Ubuntu"

#    Example that prints the loopback address and gateway for each host
    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
      when: ansible_product_uuid is defined

    - debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result.stdout_lines[0]
        
    - debug:
        msg: "{{ my_name }}"
      when: my_name == "beCloudReady"
    
    - debug:
        msg: "User input: {{user}}"

    #- name: Display all variables/facts known for a host
    #  debug:
    #    var: hostvars[inventory_hostname]

    - name: Create file with permissions
      file:
        path: /tmp/{{user}}
        state: touch
        mode: u=rw,g=r,o=r
    
    - debug:
        var: hostvars[inventory_hostname].ansible_all_ipv4_addresses[0]

    - name: Change hostname
      hostname:
        name: "{{my_name}}" 

    - name: Display some varialbes variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname].ansible_all_ipv4_addresses[0]
      # when: hostvars[inventory_hostname].ansible_all_ipv4_addresses[0] == "172.31.6.217"
