- hosts: webserver
  become: True
  tasks:
   - name: Install all the packages
     yum:
       name: '{{ item }}'
       state: present
       update_cache: True
     with_items:
      - mlocate
      - strace
      - java-1.8.0-openjdk
      - php
      - git